apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-7dpf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vnha-tenant/status-quarkus-io/statusquarkusio-7dpf@sha256:9fb530effa9da19cc303fcfb30627ce22b72174ae0ae6d91b9e26bd2ff2d7bf7
        name: my-java-quarkus
        resources: {}
status: {}
