apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-7dpf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-7dpf
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-7dpf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-7dpf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-7dpf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vnha-tenant/status-quarkus-io/statusquarkusio-7dpf@sha256:9fb530effa9da19cc303fcfb30627ce22b72174ae0ae6d91b9e26bd2ff2d7bf7
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
